[package]
name = "artifact-viewer"
version = "0.1.0"
description = "Artifact Viewer"
authors = ["Antigravity"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.0.0", features = [] }

[dependencies]
tauri = { version = "2.0.0", features = [] }
tauri-plugin-shell = "2.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.0", features = ["v4"] }
tauri-plugin-cli = "2.4.1"

[profile.release]
panic = "abort" # Strip expensive panic info
codegen-units = 1 # Optimize for size
lto = true # Enable Link Time Optimization
opt-level = "s" # Optimize for size
strip = true # Strip symbols
